stages:
  - test

common:
  stage: test
  image: registry.skillbox.ru/node:14-alpine
  before_script:
    - npm ci --no-optional
  script:
    - node -v
    - npm run test:editorconfig
    - npm run test:w3c
    - npm run test:eslint
  tags:
    - students
